# Generated by Django 5.1.6 on 2025-04-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('type', models.CharField(choices=[('daily', 'Daily Challenge'), ('random', 'Random Challenge')], default='daily', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='instagram_handle',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='points',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='twitter_handle',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='wins',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
