# Generated by Django 5.1.7 on 2025-03-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubmission',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='submission_number',
            field=models.IntegerField(default=1),
        ),
    ]
