# Generated by Django 5.1.6 on 2025-04-22 16:54

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone

def migrate_challenges_forward(apps, schema_editor):
    DailyChallenge = apps.get_model('challenges', 'DailyChallenge')
    Challenge = apps.get_model('challenges', 'Challenge')
    UserSubmission = apps.get_model('challenges', 'UserSubmission')
    
    # First, create new Challenge objects from existing DailyChallenges
    for daily in DailyChallenge.objects.all():
        challenge = Challenge.objects.create(
            title=f"Daily Challenge - {daily.date}",
            description=daily.description,
            created_at=timezone.make_aware(timezone.datetime.combine(daily.date, timezone.datetime.min.time())),
            end_date=timezone.make_aware(timezone.datetime.combine(daily.date, timezone.datetime.max.time())),
            type='daily',
            is_active=daily.is_active
        )
        
        # Update all submissions for this daily challenge to point to the new challenge
        UserSubmission.objects.filter(challenge_id=daily.id).update(challenge_id=challenge.id)

def migrate_challenges_backward(apps, schema_editor):
    Challenge = apps.get_model('challenges', 'Challenge')
    Challenge.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_challenge_remove_userprofile_about_me_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(
            migrate_challenges_forward,
            migrate_challenges_backward
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge'),
        ),
    ]
