# Generated by Django 5.1.6 on 2025-04-22 16:54

from django.db import migrations
from django.utils import timezone

def migrate_daily_challenges(apps, schema_editor):
    DailyChallenge = apps.get_model('challenges', 'DailyChallenge')
    Challenge = apps.get_model('challenges', 'Challenge')
    UserSubmission = apps.get_model('challenges', 'UserSubmission')
    
    # First, create new Challenge objects from existing DailyChallenges
    for daily in DailyChallenge.objects.all():
        challenge = Challenge.objects.create(
            title=f"Daily Challenge - {daily.date}",
            description=daily.description,
            created_at=timezone.make_aware(timezone.datetime.combine(daily.date, timezone.datetime.min.time())),
            end_date=timezone.make_aware(timezone.datetime.combine(daily.date, timezone.datetime.max.time())),
            type='daily',
            is_active=daily.is_active
        )
        
        # Update all submissions for this daily challenge to point to the new challenge
        UserSubmission.objects.filter(challenge_id=daily.id).update(challenge_id=challenge.id)

class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_usersubmission_feedback_usersubmission_score_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_daily_challenges),
    ]
