# Generated by Django 5.1.7 on 2025-03-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_userprofile_about_me_userprofile_instagram_handle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailychallenge',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='category',
            field=models.CharField(choices=[('character', 'Character Design'), ('landscape', 'Landscapes'), ('abstract', 'Abstract Art'), ('concept', 'Concept Art'), ('portrait', 'Portraits'), ('scifi', 'Sci-Fi'), ('fantasy', 'Fantasy'), ('anime', 'Anime Style'), ('realistic', 'Realistic'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='dailychallenge',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
