# Generated by Django 5.1.6 on 2025-04-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_auto_20250422_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
